services:
  bgutil-pot:
    image: brainicism/bgutil-ytdlp-pot-provider
    container_name: bgutil-pot
    restart: unless-stopped
    ports:
      - "4416:4416"

  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    depends_on:
      - bgutil-pot
    environment:
      BGUTIL_BASE_URL: "http://bgutil-pot:4416"
      USE_COOKIES: "false"
      USE_ARIA2C_FOR_VIDEO_FALLBACK: "false"
    env_file:
      - .env